[supervisord]
nodaemon=true

[program:srs]
command=/usr/local/srs/objs/srs -c /usr/local/srs/conf/srs.conf
autostart=true
autorestart=true

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
